/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import DAO.KhachHangDao;
import MODEL.KhachHang;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author daiun
 */
public class frmQLKhachHang extends javax.swing.JInternalFrame {
    List<KhachHang> listKH = new ArrayList<>();
    DefaultTableModel tblModel = new DefaultTableModel();
    int index = 0;
    /**
     * Creates new form frmQLKhachHang
     */
    public frmQLKhachHang() {
        initComponents();
        fillDataToTable();
    }
    
    private void setEditable(boolean enable) {
    txtMaKH.setEditable(enable);
    txtHoKH.setEditable(enable);
    txtTenKH.setEditable(enable);
    txtCMND.setEditable(enable);
    txtDienThoai.setEditable(enable);
    txtDiaChi.setEditable(enable);
    txtGhiChu.setEditable(enable);
    rd_Nam.setEnabled(enable);
    rd_Nu.setEnabled(enable);
}
    public void fillDataToTable() {
    KhachHangDao khDao = new KhachHangDao();
    listKH = khDao.XemThongTin();
    tblModel = (DefaultTableModel) tblKhachHang.getModel();
    tblModel.setRowCount(0);
    for (KhachHang kh : listKH) {
        Object[] row = new Object[]{
            kh.getMaKH(),
            kh.getHoKH(),
            kh.getTenKH(),
            kh.GioiTinh(),
            kh.getCMND(),
            kh.getDienThoai(),
            kh.getDiaChi(),
        };
        tblModel.addRow(row);
    }
    tblKhachHang.setModel(tblModel);
}
    public void showForm() {
    index = tblKhachHang.getSelectedRow();
    if (index < 0) {
        JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng trên bảng");
        return;
    } else {
        KhachHang kh = listKH.get(index);
        txtMaKH.setText(kh.getMaKH());
        txtHoKH.setText(kh.getHoKH());
        txtTenKH.setText(kh.getTenKH());
        txtCMND.setText(kh.getCMND());
        txtDienThoai.setText(kh.getDienThoai());
        if (kh.getGioiTinh() == 1) {
            rd_Nam.setSelected(true);
        } else {
            rd_Nu.setSelected(true);
        }
        txtDiaChi.setText(kh.getDiaChi());
        txtGhiChu.setText(kh.getGhiChu());
        setEditable(true);
    }
}
    public void clearForm() {
    txtMaKH.setText("");
    txtHoKH.setText("");
    txtTenKH.setText("");
    txtCMND.setText("");
    txtDienThoai.setText("");
    rd_Nam.setSelected(false);
    rd_Nu.setSelected(false);
    txtDiaChi.setText("");
    txtGhiChu.setText("");
}

    public void xemThongTin(String tim)
    {
        tim = txt_Tim.getText();
        KhachHangDao khDao = new KhachHangDao();
        listKH = khDao.TimTheoMa(tim);
        tblModel = (DefaultTableModel) tblKhachHang.getModel();
        tblModel.setRowCount(0);
        for (KhachHang kh : listKH) {
            Object[] row = new Object[]{
                kh.getMaKH(),
                kh.getHoKH(),
                kh.getTenKH(),
                kh.GioiTinh(),
                kh.getCMND(),
                kh.getDienThoai(),
                kh.getDiaChi(),
            };
            tblModel.addRow(row);
        }
        tblKhachHang.setModel(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        panelCustomerInfomation = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rd_Nam = new javax.swing.JRadioButton();
        rd_Nu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Tim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanel1.setAutoscrolls(true);

        tblKhachHang.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Họ KH", "Tên KH", "Giới tính", "CMND", "Điện thoại", "Địa chỉ"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhachHang);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCustomerInfomation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Mã KH:");

        txtMaKH.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Họ:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Tên:");

        txtHoKH.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtHoKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoKHKeyTyped(evt);
            }
        });

        txtTenKH.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtTenKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTenKHKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("CMND:");

        txtCMND.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCMNDKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Điện thoại:");

        txtDienThoai.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDienThoaiKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Địa chỉ:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Ghi chú:");

        txtGhiChu.setEditable(false);
        txtGhiChu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Giới tính:");

        buttonGroup1.add(rd_Nam);
        rd_Nam.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rd_Nam.setSelected(true);
        rd_Nam.setText("Nam");

        buttonGroup1.add(rd_Nu);
        rd_Nu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rd_Nu.setText("Nữ");

        txtDiaChi.setColumns(20);
        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtDiaChi.setRows(5);
        txtDiaChi.setTabSize(6);
        jScrollPane1.setViewportView(txtDiaChi);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add.png"))); // NOI18N
        btnThem.setToolTipText("Thêm");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        btnSua.setToolTipText("Sửa");
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/delete.png"))); // NOI18N
        btnXoa.setToolTipText("Xóa");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/refresh.png"))); // NOI18N
        btnClean.setToolTipText("Làm rỗng các ô nhập liệu");
        btnClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Customer.png"))); // NOI18N
        jLabel12.setText("Thông tin khách hàng");

        javax.swing.GroupLayout panelCustomerInfomationLayout = new javax.swing.GroupLayout(panelCustomerInfomation);
        panelCustomerInfomation.setLayout(panelCustomerInfomationLayout);
        panelCustomerInfomationLayout.setHorizontalGroup(
            panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerInfomationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomerInfomationLayout.createSequentialGroup()
                        .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCustomerInfomationLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenKH)
                                    .addComponent(txtHoKH)
                                    .addGroup(panelCustomerInfomationLayout.createSequentialGroup()
                                        .addComponent(rd_Nam)
                                        .addGap(48, 48, 48)
                                        .addComponent(rd_Nu)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCMND)
                                    .addComponent(txtDienThoai)))
                            .addGroup(panelCustomerInfomationLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCustomerInfomationLayout.createSequentialGroup()
                                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnClean))
                                    .addComponent(txtGhiChu, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1))))
                        .addGap(10, 10, 10))
                    .addGroup(panelCustomerInfomationLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelCustomerInfomationLayout.setVerticalGroup(
            panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerInfomationLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(11, 11, 11)
                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rd_Nam)
                    .addComponent(rd_Nu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomerInfomationLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomerInfomationLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addGroup(panelCustomerInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnClean)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN KHÁCH HÀNG");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("DANH SÁCH KHÁCH HÀNG HIỆN CÓ");

        txt_Tim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TimKeyReleased(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Search.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCustomerInfomation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(27, 27, 27)
                        .addComponent(txt_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel10)
                        .addComponent(btnTim))
                    .addComponent(txt_Tim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCustomerInfomation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        showForm();
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void txt_TimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TimKeyReleased

    }//GEN-LAST:event_txt_TimKeyReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        KhachHangDao khDao = new KhachHangDao();
        KhachHang kh = new KhachHang();
        kh.setMaKH(txtMaKH.getText());
        kh.setHoKH(txtHoKH.getText());
        kh.setTenKH(txtTenKH.getText());
        kh.setCMND(txtCMND.getText());
        kh.setDienThoai(txtDienThoai.getText());
        if (rd_Nam.isSelected()) {
            kh.setGioiTinh(1);
        } else {
            kh.setGioiTinh(0);
        }
        kh.setDiaChi(txtDiaChi.getText());
        kh.setGhiChu(txtGhiChu.getText());
        int x = khDao.them(kh);
        if (x > 0) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            fillDataToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        setEditable(true);
        txtMaKH.setEditable(false);
        KhachHangDao khDao = new KhachHangDao();
        KhachHang kh = new KhachHang();
        kh.setMaKH(txtMaKH.getText());
        kh.setHoKH(txtHoKH.getText());
        kh.setTenKH(txtTenKH.getText());
        if (rd_Nam.isSelected()) {
            kh.setGioiTinh(1);
        } else {
            kh.setGioiTinh(0);
        }
        kh.setCMND(txtCMND.getText());
        kh.setDienThoai(txtDienThoai.getText());
        kh.setDiaChi(txtDiaChi.getText());
        kh.setGhiChu(txtGhiChu.getText());
        int x = khDao.sua(kh);
        if (x > 0) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            fillDataToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String maKH = txtMaKH.getText().trim(); 
        if (maKH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng muốn xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa khách hàng này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            KhachHangDao khDao = new KhachHangDao();
            int x = khDao.xoa(maKH);
            if (x > 0) {
                fillDataToTable(); 
                JOptionPane.showMessageDialog(this, "Đã xóa khách hàng thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa khách hàng thất bại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        setEditable(true);
        clearForm();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        xemThongTin(txt_Tim.getText());
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtHoKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoKHKeyTyped
        // TODO add your handling code here:
                char ten = evt.getKeyChar();
        if (!Character.isLetter(ten) && !Character.isISOControl(ten)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtHoKHKeyTyped

    private void txtTenKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKHKeyTyped
        // TODO add your handling code here:
                char ten = evt.getKeyChar();
        if (!Character.isLetter(ten) && !Character.isISOControl(ten)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTenKHKeyTyped

    private void txtDienThoaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDienThoaiKeyTyped
        // TODO add your handling code here:
                char sdt = evt.getKeyChar();
        String text = ((javax.swing.JTextField) evt.getSource()).getText();

        // Giới hạn ký tự nhập vào chỉ là số
        if (!Character.isDigit(sdt)) {
            evt.consume();
        }

        // Giới hạn độ dài tối đa là 10 ký tự
        if (text.length() >= 10) {
            evt.consume();
        }

        // Bắt buộc ký tự đầu tiên phải là số 0
        if (text.isEmpty() && sdt != '0') {
            evt.consume();
        }
    }//GEN-LAST:event_txtDienThoaiKeyTyped

    private void txtCMNDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMNDKeyTyped
        // TODO add your handling code here:
                char cmnd = evt.getKeyChar();
        String text = ((javax.swing.JTextField) evt.getSource()).getText();

        // Giới hạn ký tự nhập vào chỉ là số
        if (!Character.isDigit(cmnd)) {
            evt.consume();
        }

        // Giới hạn độ dài tối đa là 10 ký tự
        if (text.length() >= 12) {
            evt.consume();
        }

        // Bắt buộc ký tự đầu tiên phải là số 0
        if (text.isEmpty() && cmnd != '0') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCMNDKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelCustomerInfomation;
    private javax.swing.JRadioButton rd_Nam;
    private javax.swing.JRadioButton rd_Nu;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoKH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txt_Tim;
    // End of variables declaration//GEN-END:variables
}
